###
GET http://localhost:3005/api/items

###
POST http://localhost:3005/api/items
Content-Type: application/json

{
    "id": "17",
    "title": "car"
}

###
DELETE http://localhost:3005/api/items/3

###
GET http://localhost:3005/api/items/?limit=2