###
GET http://localhost:3005/api/items

###
POST http://localhost:3005/api/items/post
Content-Type: application/json

{
    "id": "26",
    "title": "keyboard"
}

###
DELETE http://localhost:3005/api/items/26

###
GET http://localhost:3005/api/items/?limit=5